Algoritmo "Caractere Vs Inteiro"

Var
    palavra1, palavra2, palavra3: caractere
    numero1, numero2, numero3: inteiro

Inicio
     Escreval("  ==================")
     Escreval("== TESTE DE TIPAGEM ==")
     Escreval("  ==================")
     Escreval(" ")
     Escreval("-----------------------")
     Escreval("Palavra 1: ")
     leia(palavra1)
     Escreval("-----------------------")
     Escreval("Palavra 2: ")
     leia(palavra2)
     Escreval("-----------------------")
     Escreval("Número 1: ")
     leia(numero1)
     Escreval("-----------------------")
     Escreval("Número 2: ")
     leia(numero2)
     
     palavra3 <- palavra1 + palavra2
     numero3 <- numero1 + numero2
     
     Escreval("======================")
     Escreval(palavra3)
     Escreval(numero3)
     Escreval("======================")
     Escreval(" ")
     
     Escreval("       ==========")
     Escreval("     == OBRIGADO ==")
     Escreval("       ==========")
     




Fimalgoritmo