Algoritmo "MOD e DIV"

Var
     x, y, w, p: inteiro

Inicio
     Escreval("    =============")
     Escreval("   == DIV & MOD ==")
     Escreval("    =============")
     Escreval(" ")
     Escreval("        =====")
     Escreval("         DIV")
     Escreval("        =====")
     Escreval("     ------------")
     Escreva("      10 / 3 =") // O DIV retorna a parte inteira de uma
                               // divisão não-Exata.
     X <- 10
     Y <- 3
     W <- X DIV y
     
     Escreval(w)
     Escreval("     ------------")
     
     Escreval("======================")
     Escreval(" ")
     Escreval("        =====")
     Escreval("         MOD")
     Escreval("        =====")
     Escreval("     ------------")
     Escreva("Informe um número: ") // O MOD retorna o resto de uma divisão;
     leia(p)                        // Geralmente usado para determinar se é PAR ou
     se p MOD 2 = 1 entao           // IMPAR.
         Escreval("Número IMPAR")
     senao
         Escreval("Número PAR")
     fimse
     
     Escreval(" ")

     Escreval("       ==========")
     Escreval("     == OBRIGADO ==")
     Escreval("       ==========")
     




Fimalgoritmo