Algoritmo "Trabalhando com tipos de Variáveis"

Var
     nome, sobrenome, nomeCompleto: caractere

Inicio
     Escreval("  ==================")
     Escreval("== CADASTRO SIMPLES ==")
     Escreval("  ==================")
     Escreval(" ")
     Escreval("-----------------------")
     Escreval("Informe seu nome: ")
     leia(nome)
     Escreval("-----------------------")
     Escreval("Informe seu sobrenome: ")
     leia(sobrenome)
     Escreval("-----------------------")
     
     nomeCompleto <- nome + " " + sobrenome
     
     Escreval(nomeCompleto)
     Escreval("-----------------------")
     
     Escreval("       ==========")
     Escreval("     == OBRIGADO ==")
     Escreval("       ==========")
     




Fimalgoritmo